config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#home'
  resources :charges
  resources :purchases, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/purchase.rb
class Purchase < ApplicationRecord
	def to_param
		uuid
	end

	def email_purchaser
		PurchaseMailer.purchase_receipt(self) .deliver
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def create

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :source  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => params[:amount],
	    :description => 'Rails Stripe customer',
	    :currency    => 'usd'
	  )

		purchase = Purchase.create(email: params[:stripeEmail], card: params[:stripeToken], amount: params[:amount], description: charge.description, currency: charge.currency, customer_id: customer.id, product_id:1, uuid: SecureRandom.uuid)
		redirect_to purchase

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to new_charge_path
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def home
	end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def show
		@purchase = Purchase.find_by_uuid(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPayments</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, user-scalable=no">
    <link rel='stylesheet' href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,800' >
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div id="content" class="container">
      <header id="content-header">
        <div id="price-container">
          <span class="glyphicon glyphicon-tag"></span><span class="price">$9.99</span>
        </div>
        <%= image_tag('header-image.jpg', id:"content-head-img", alt:"Learn Rails") %>
      </header>
      <%= yield %>
    </div>
    <footer id="site-footer">
    Made by <a href="#" target="_blank">Learn App Code</a>
    </footer>
  </body>
</html>

app/views/layouts/purchase_mailer.html.erb
<!DOCTYPE html>
<html>
	<head> 
		<title>Your title</title>
	</head> 

	<body> 

		<%= yield %>
		<p> Thanks for your purchase! </p>

	</body> 
</html>

app/views/pages/home.html.erb
    <section id="content-details" class="row clearfix">
        <article id="details-article" class="col-sm-8">
            <h1 id="article-title">Your Product <span class="font-weight-light">Product Name</span></h1>
           

            <p>Lorem ipsum dolor sit amet, in nam feugiat eleifend. Sea an possit offendit definiebas, usu cu aeque mediocritatem. Vis constituam suscipiantur ad, cum duis concludaturque no. Sea vocent consulatu at.</p>

            <p>Lorem ipsum dolor sit amet, pri id tractatos torquatos, eruditi alienum eam ad. Sint graeci mel te. Ex eius corrumpit.</p>
            <p><strong>What You Get</strong></p>
            <ul class="no-indent">
                <li>Lorem ipsum dolor sit.</li>
                <li>Lorem ipsum dolor sit amet, cum.</li>
                <li>Lorem ipsum dolor sit amet, quo ne etiam.</li>
            </ul>
        </article>
        <aside id="details-aside" class="col-sm-4">

            <%= form_tag charges_path, id:'chargeForm' do %>

                    <% if flash[:error].present? %>
                        <div id="error_explanation">
                            <p><%= flash[:error] %></p>
                        </div>
                    <% end %>

                <script src="https://checkout.stripe.com/checkout.js"></script>
                <%= hidden_field_tag 'stripeToken' %>
                <%= hidden_field_tag 'amount', 499 %>
                <%= hidden_field_tag 'stripeEmail' %>
                <button id="btn-buy" type="button" class="btn btn-success btn-lg btn-block"><span class="glyphicon glyphicon-ok"></span>Buy this!</button>
<script>
    var handler = StripeCheckout.configure({
      key: '<%= Rails.configuration.stripe[:publishable_key] %>',
      token: function(token, arg) {
        document.getElementById("stripeToken").value = token.id;
        document.getElementById("stripeEmail").value = token.email;
        document.getElementById("chargeForm").submit();
      }
});
document.getElementById('btn-buy').addEventListener('click', function(e) {
      handler.open({
        name: 'Learn Rails',
        description: 'Buy this item for ($4.99)',
        amount: document.getElementById("amount").value
    });
    e.preventDefault();
   })
</script>
            <% end %>
            <ul id="details-infobox" class="list-group">
              <li class="list-group-item active clearfix">Info</li>
              <li class="list-group-item">What You Get</li>
              <li class="list-group-item">This Is Included</li>
            </ul>
        </aside>
    </section>
<footer id="site-footer">
Made by <a href="#" target="_blank"><p>Learn Rails</p></a>
</footer>

app/views/purchases/show.html.erb
    <section id="content-receipt" class="clearfix">
      <div id="receipt-container">
        <div class="dotmatrix left"></div>
        <div id="receipt-content">
          <h4 id="receipt-title">Thank You!</h4>
          <p><strong>RECEIPT</strong></p>
          <div id="receipt-details" class="row clearfix">
            <div class="col-sm-8 receipt-left">
              <p><strong class="font-weight-heavy">Your Product</strong><br/> <span class="font-weight-light">What you sold</span></p>
            </div>
            <div class="col-sm-4">
              $4.99
            </div>
          </div>
					<a href="https://s3-us-west-2.amazonaws.com/rails-payments-app/cover1.jpg">
          <button type="button" class="btn btn-success btn-xs">DOWNLOAD</button></a>
          <footer id="receipt-footer">
            <small>Your purchase is complete. We hope you enjoy it!</small>
          </footer>
        </div>
        <div class="dotmatrix right"></div>
      </div>
      <div id="receipt-shadow"></div>
    </section>